# Generated by Django 2.1 on 2018-08-27 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memword', '0002_move_association_into_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('exam', 'Exam'), ('notification', 'Notification')], max_length=12)),
                ('confidence_level', models.IntegerField(help_text='This should be between 1 and 10')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_seen', models.DateTimeField(null=True)),
                ('date_sent', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repetition',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memword.Target'),
        ),
    ]
