# Generated by Django 2.1 on 2018-08-28 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memword', '0003_add_repetition_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetition',
            name='scheduled_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repetition',
            name='confidence_level',
            field=models.IntegerField(help_text='This should be between 1 and 10', null=True),
        ),
    ]
