# Generated by Django 2.1 on 2018-08-28 05:47
from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def days_in_seconds(days):
    return int(timedelta(days=days).total_seconds())

DEFAULT_INTERVALS = {
    '0_1': days_in_seconds(1),
    '1_2': days_in_seconds(1),
    '2_3': days_in_seconds(2),
    '3_4': days_in_seconds(2),
    '4_5': days_in_seconds(3),
    '5_6': days_in_seconds(4),
    '6_7': days_in_seconds(5),
    '7_8': days_in_seconds(6),
    '8_9': days_in_seconds(7),
    '9_10': days_in_seconds(10),
    '10_11': days_in_seconds(10),
    '11_12': days_in_seconds(10),
    '12_13': days_in_seconds(10),
    '13_14': days_in_seconds(10),
    '14_15': days_in_seconds(10),
    '15_16': days_in_seconds(10),
    '16_17': days_in_seconds(10),
    '17_18': days_in_seconds(10),
    '18_19': days_in_seconds(10),
    '19_20': days_in_seconds(10),
}


def populate_default_row(apps, schema_editor):
    UserLearningIntervals = apps.get_model('memword', 'UserLearningIntervals')
    if UserLearningIntervals.objects.filter(id=1).exists():
        return

    default_row = UserLearningIntervals.objects.create(id=1)
    for i in range(20):
        field_name = '%s_%s' % (i, i + 1)
        setattr(default_row, field_name, DEFAULT_INTERVALS[field_name])

    default_row.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memword', '0004_add_repetition_scheduled_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('0_1', models.IntegerField(help_text='in seconds', null=True)),
                ('1_2', models.IntegerField(help_text='in seconds', null=True)),
                ('2_3', models.IntegerField(help_text='in seconds', null=True)),
                ('3_4', models.IntegerField(help_text='in seconds', null=True)),
                ('4_5', models.IntegerField(help_text='in seconds', null=True)),
                ('5_6', models.IntegerField(help_text='in seconds', null=True)),
                ('6_7', models.IntegerField(help_text='in seconds', null=True)),
                ('7_8', models.IntegerField(help_text='in seconds', null=True)),
                ('8_9', models.IntegerField(help_text='in seconds', null=True)),
                ('9_10', models.IntegerField(help_text='in seconds', null=True)),
                ('10_11', models.IntegerField(help_text='in seconds', null=True)),
                ('11_12', models.IntegerField(help_text='in seconds', null=True)),
                ('12_13', models.IntegerField(help_text='in seconds', null=True)),
                ('13_14', models.IntegerField(help_text='in seconds', null=True)),
                ('14_15', models.IntegerField(help_text='in seconds', null=True)),
                ('15_16', models.IntegerField(help_text='in seconds', null=True)),
                ('16_17', models.IntegerField(help_text='in seconds', null=True)),
                ('17_18', models.IntegerField(help_text='in seconds', null=True)),
                ('18_19', models.IntegerField(help_text='in seconds', null=True)),
                ('19_20', models.IntegerField(help_text='in seconds', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(code=populate_default_row, reverse_code=lambda *args, **kwargs: True)
    ]
