# Generated by Django 2.1 on 2018-09-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memword', '0008_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='questions',
        ),
        migrations.AddField(
            model_name='lesson',
            name='targets',
            field=models.ManyToManyField(through='memword.Question', to='memword.Target'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memword.Lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='memword.Target'),
        ),
    ]
