# Generated by Django 2.1 on 2018-09-09 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memword', '0009_fix_custom_through_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='planned_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
