# Generated by Django 2.1 on 2018-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memword', '0010_lesson_planned_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pass_time',
            field=models.DateTimeField(null=True),
        ),
    ]
