# Generated by Django 2.1 on 2019-01-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memword', '0011_question_pass_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.FloatField(default=1)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memword.Target')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
