# Generated by Django 2.1.5 on 2019-02-05 15:32

from django.db import migrations, models


def mark_existing_targets_as_verified(apps, schema_editor):
    Target = apps.get_model('memword', 'Target')
    Target.objects.all().update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('memword', '0012_targetdifficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(code=mark_existing_targets_as_verified,
                             reverse_code=lambda *args, **kwargs: True)
    ]
