# Generated by Django 2.1 on 2019-01-22 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memword', '0012_targetdifficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField()),
                ('preferred_time', models.TimeField(null=True)),
                ('last_generation_time', models.DateTimeField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('questions_count', models.IntegerField(default=10)),
                ('lesson_type', models.CharField(choices=[('lecture', 'Lecture'), ('exam', 'Exam')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
